### ISSUE TITLE
Gnome Settings Sound Test does not work

### ISSUE THREAD

**Issue by LiberalTugboat** [Vanilla-OS/gnome-control-center#11]
On a fresh install from build #59. Audio on my HP Envy is working, but the "Test" function in Gnome Settings > Sound does not work. The modal window opens, but clicking the "Front Left" or "Front Right" does not trigger the test sounds.

**Comment by kbdharun** [comment]
> On a fresh install from build #59. Audio on my HP Envy is working, but the "Test" function in Gnome Settings > Sound does not work. The modal window opens, but clicking the "Front Left" or "Front Right" does not trigger the test sounds.

I checked this out, Along with this, the Output sound doesn't seem to work at all. (I am on a PC, not on a laptop).

**Comment by mirkobrombin** [comment]
It is missing a dependency: https://bugs.launchpad.net/ubuntu/+source/gnome-control-center/+bug/1983638
