### ISSUE TITLE
No unlock button for Printers

### ISSUE THREAD

**Issue by LiberalTugboat** [Vanilla-OS/gnome-control-center#12]
Fresh install build #59.
In Gnome Settings > Printers, the dialog at the top of the window says "Unlock to Change Settings", but there is no Unlock button and the blue "Add Printer" button is greyed out.
I was able to add my Epson ET-3760 printer with the "Addtional Printer Settings" button.

**Comment by kbdharun** [comment]
I will test out printing from Vanilla os and will check whether it's replicable. Thanks for the report.

**Comment by kbdharun** [comment]
> Fresh install build #59. In Gnome Settings > Printers, the dialog at the top of the window says "Unlock to Change Settings", but there is no Unlock button and the blue "Add Printer" button is greyed out. I was able to add my Epson ET-3760 printer with the "Addtional Printer Settings" button.

Yes, I tried it out this seems to be a bug.  If you have a network printer like me it gets automatically detected. But I am not able to unlock it @Muqtxdir can you check this issue? These are some workarounds

1. As you said is adding the printer through `Additional Printer Settings`. Which can also be invoked from the terminal using the `system-config-printer`.
2. Or through https://localhost:631 (OpenPrinting CUPS).

**Comment by kbdharun** [comment]
Update: Installing `cups-pk-helper` (https://www.freedesktop.org/wiki/Software/cups-pk-helper/) fixed the issue. I was surprised to see that it wasn't installed. For the current build, we need to use `sudo abroot exec apt install cups-pk-helper`. In future, we need to add this dependency to the package and patch it.
