### ISSUE TITLE
Windows Setting conflicts with GNOME Tweaks

### ISSUE THREAD

**Issue by Khayasen** [Vanilla-OS/gnome-control-center#14]
When we switch the window buttons (Close, Minimize, Maximize) to the left via `gnome-tweaks`, and then we open the Windows setting in `gnome-control-center,` it automatically adds another close button on the right.

This issue could be fixed by editing variables in dconf to `close:appmenu`.

Possible fix: Add "move button to left side" option in Windows setting in `gnome-control-center`

**Comment by Muqtxdir** [comment]
hi @Khayasen 

thanks for pointing out this issue, i have just committed the change that should force only the options provided by us whenver `gnome-control-center` is opened.

also the update should hit you in 2 or 3hrs via launchpad
