### ISSUE TITLE
Orchid changes

### ISSUE THREAD

**Issue by mirkobrombin** [Vanilla-OS/gnome-control-center#16]
With the idea of transforming the VCC into the Apx container manager, the following functions need to be re-implemented in GCC:
- [x] Drivers installation
- [x] PRIME Profiles switcher

**Comment by mirkobrombin** [comment]
This will start in 22.10 r8 and will be completed in ~~23.04~~ 2.0.

**Comment by TheEvilSkeleton** [comment]
As discussed on Discord, PRIME will be under the Displays panel (now in main https://github.com/Vanilla-OS/gnome-control-center/commit/edfefee7512ab8094cd11708c310c707efb4c0f5), and drivers installation in the About panel.

We agreed that the placement of drivers installation is temporarily, as it was rushed. We are okay with doing something "ugly" for the time being, as long as we have a proper solution later.

My opinion on this is that managing drivers, e.g. choosing specific versions, should be done in the CLI, as it is an advanced feature, and only a subset of users would want to choose specific versions for whatever reason. Installing and applying the latest versions should be automatically done in GNOME Software.
