### ISSUE TITLE
Add more title bar button variation

### ISSUE THREAD

**Issue by Khayasen** [Vanilla-OS/gnome-control-center#20]
As of now, the current configurations available for window titlebar buttons in the control center is either close button only (at the right corner) or the triple button combo (also at the right).

But several people like me prefer the close button to be on the left, so please give the option or at least don't force the button to be on the right even after we configured it via gnome-tweaks.

**Comment by TheEvilSkeleton** [comment]
I completely disagree. There's been an overwhelming amount of discussion between GNOME designers about making titlebar buttons accessible in Settings. The answer was always disapproval, as it goes against the workflow.

Since this option is in Tweaks, it should stay there.

**Comment by GabsEdits** [comment]
It should be "Vanilla"

**Comment by Muqtxdir** [comment]
soon with newer release, the windows panel will be dropped. so you can go back to gnome-tweaks for your titlebar prefrerences
