### ISSUE TITLE
include common mouse and touchpad settings

### ISSUE THREAD

**Issue by Muqtxdir** [Vanilla-OS/gnome-control-center#4]
- patches to expose common mouse and touchpad settings that are kinda only be configured via GNOME Tweaks such as:
   - [x] touchpad: disable while typing (_done with commit:_ f02bd858c8f986068d4328622d74ffff8e783d7c)
   - [x] touchpad: mouse click emulation (_done with commit:_ 88e2c9e111f396d37914600720c2d3ec5ae5c14f)
   - [x] mouse: pointer location (_done with commit:_ 88e2c9e111f396d37914600720c2d3ec5ae5c14f)
   - [x] mouse: acceleration profile (_done with commit:_ 88e2c9e111f396d37914600720c2d3ec5ae5c14f, still need to fix this one)

_something similar to commit:_ de123baf649b4abcd2727443aea34bc05aa8cd2c

**Comment by Muqtxdir** [comment]
will look into making this one more organized, as the settings for `touchpad` group by default are still confusing.

**Comment by Muqtxdir** [comment]
so this what ive been upto: 
- the assets are pain to do (_need to make sure it looks good on both default and dark_) but i think this looks nice?

| mouse | touchpad |
| --------- | -------------|
| ![image](https://user-images.githubusercontent.com/54065734/203332449-a72adb30-3468-4ae3-9e28-30079db0277a.png) | ![image](https://user-images.githubusercontent.com/54065734/203333210-77a5c965-9578-4782-a56b-c4b2af31187b.png) |
| ![image](https://user-images.githubusercontent.com/54065734/203333895-132d9acc-6fb3-4357-8eb3-eff6d43b3118.png) | ![image](https://user-images.githubusercontent.com/54065734/203333984-33494b12-9361-4b66-a1f4-5e466c637a84.png) |



taken from _mockups:_ https://gitlab.gnome.org/Teams/Design/settings-mockups/-/issues/9

**Comment by mirkobrombin** [comment]
looks nice!

**Comment by Muqtxdir** [comment]
alrighty, done with this in commit: aff1e02b4934c2d75eb658dd0d7f7c5b6ecfa28a

### screen-demo:
https://user-images.githubusercontent.com/54065734/204088660-dfdf6e0a-8297-4f65-9708-bca366f4a777.mp4
