### ISSUE TITLE
window titlebars

### ISSUE THREAD

**Issue by Muqtxdir** [Vanilla-OS/gnome-control-center#5]
- introduce new panel in settings that presents
   - [x] titlebar buttons: expose option to switch from default (_only close titlebar button_) to extended (_all titlebar buttons_)
   - [x] attach modal dialogs
   - [x] center new windows
   - [x] resize with secondary click
   - [x] window focus: click to focus, focus on hover, secondary click

**Comment by mirkobrombin** [comment]
I think it's a good idea, in this way the experience is still vanilla and advanced users can still change the behavior in a controlled way

**Comment by Muqtxdir** [comment]
aight, this is completed with commit: 4244ee57d3ba02ac7e8b823db32256f2734350cd

### screen-demo:

https://user-images.githubusercontent.com/54065734/204131471-a1864c25-5a43-439f-87ac-9efb497ce9f0.mp4
